
server {
    listen 80;

    location = /app {
        return 301 /app/;
    }

    # Static assets
    location /app/assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    # SPA frontend
    location /app/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /app/index.html;
    }
}
