apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    version: v2
spec:
  selector:
    matchLabels:
      version: v2
  template:
    metadata:
      labels:
        version: v2
    spec:
      containers:
      - name: monitor
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: monitor-config
      restartPolicy: Always
