---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-v1
  labels:
    app: monitor
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
      version: v1
  template:
    metadata:
      labels:
        app: monitor
        version: v1
    spec:
      serviceAccountName: monitor-sa
      containers:
      - name: monitor
        image: docker.io/mcbtaguiad/istio-demo:monitor
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: monitorv1.environment
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-v2
  labels:
    app: monitor
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
      version: v2
  template:
    metadata:
      labels:
        app: monitor
        version: v2
    spec:
      serviceAccountName: monitor-sa
      containers:
      - name: monitor
        image: docker.io/mcbtaguiad/istio-demo:monitor
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: monitorv2.environment
      restartPolicy: Always
