---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    tier: db
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: db
  template:
    metadata:
      labels:
        app: redis
        tier: db
    spec:
      serviceAccountName: redis-sa
      containers:
      - name: redis
        image: docker.io/bitnami/redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        envFrom:
        - configMapRef:
            name: redis.environment
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
    tier: db
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis.environment
immutable: false
data:
  ALLOW_EMPTY_PASSWORD: 'yes'
  REDIS_DISABLE_COMMANDS: 'FLUSHDB,FLUSHALL'
