resources:
  - ../../base

nameSuffix: -v2

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: backend

  - path: service-patch.yaml
    target:
      kind: Service
      name: backend

  # - path: name-patch.json
  #   target:
  #     kind: Service
  #     name: monitor
  #
  # - path: name-patch.json
  #   target:
  #     kind: Deployment
  #     name: monitor


configMapGenerator:
- name: backend-config
  literals:
  - VERSION=2.0.0.
  - ALLOWED_HOSTS=http://192.168.254.230
  - REDIS_ADDR=redis:6379
