---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: read-monitor-to-backend 
spec:
  selector:
    matchLabels:
      app: backend
  action: ALLOW
  rules:
  - from:
    - source:
        principals: 
        - "cluster.local/ns/demo/sa/monitor-sa"
        - "cluster.local/ns/demo/sa/demo-app-gateway-istio"
    to:
    - operation:
        methods: ["GET", "POST"]
        paths:
        - "/api/login"
        - "/api/version"
        - "/api/users"
        - "/api/users/*" # delete user
