apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: redis-config
  literals:
  - ALLOW_EMPTY_PASSWORD=yes
  - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
