apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - namespace.yaml

  # shared/common (ONLY ONCE)
  - ../../backend/common
  - ../../monitor/common

  # versions
  - ../../backend/overlays/v1
  - ../../backend/overlays/v2
  - ../../monitor/overlays/v1
  - ../../monitor/overlays/v2

  # others
  - ../../frontend/base
  - ../../redis/base

  # istio
  - ../../istio/base


patches:
- target:
    group: security.istio.io
    version: v1
    kind: AuthorizationPolicy
    name: read-write-frontend-to-backend 
  path: frontend-authpolicy-patch.yaml

- target:
    group: security.istio.io
    version: v1
    kind: AuthorizationPolicy
    name: read-write-monitor-to-backend
  path: monitor-authpolicy-patch.yaml
