apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: backend-destinationrule
spec:
  host: backend
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 200
        connectTimeout: 2s
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 20
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 25

---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: monitor-destinationrule
spec:
  host: monitor
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 200
        connectTimeout: 2s
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 20
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 25


---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: frontend-destinationrule
spec:
  host: frontend
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 2s
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 25

