apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- destinationrule.yaml
- gateway.yaml
- virtualservice.yaml
- mtls.yaml
- rbac-readwrite-frontend-to-backend.yaml
- rbac-readwrite-monitor-to-backend.yaml
