resources:
  - ../../base

nameSuffix: -v1

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: monitor

  - path: service-patch.yaml
    target:
      kind: Service
      name: monitor

  # - path: name-patch.json
  #   target:
  #     kind: Service
  #     name: monitor
  #
  # - path: name-patch.json
  #   target:
  #     kind: Deployment
  #     name: monitor


configMapGenerator:
- name: monitor-config
  literals:
  - VERSION=1.0.0
  - DEMO_APP_HOST=http://192.168.254.230
