name: tags-cicd
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.repo-path.outputs.path }}
    steps:
      - name: Checkout repository
        id: repo-path
        uses: actions/checkout@v4
  # --- Python Tests ---
  python-test:
    needs: checkout

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12.8] 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install flask pytest pylint black flake8 isort pytest-cov

      - name: Run pytest
        run: pytest repo/docker/monitor --cov=repo/docker/monitor

      - name: Lint with pylint
        run: pylint repo/docker/monitor/app.py

      - name: Format check with black
        run: black --check repo/docker/monitor/app.py

      - name: Import check with isort
        run: isort --check-only repo/docker/monitor/app.py

  # --- React Tests ---
  react-test:
    needs: checkout

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: docker/frontend/package-lock.json

      - name: Install dependencies
        working-directory: docker/frontend
        run: npm ci   # ✅ deterministic install

      - name: Run React tests
        working-directory: docker/frontend
        run: npm run test -- --coverage
