name: tags-cicd

on:
  push:
    branches: [ "main" ]
    # Trigger on tag creation
    tags: [ 'v*' ]  # Matches any tags starting with 'v', e.g., v1.0.0
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}

jobs:

  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.repo-path.outputs.path }}
    steps:
      - name: Checkout repository
        id: repo-path
        uses: actions/checkout@v4

  # --- Go Tests ---
  backend-test:
    needs: checkout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.26.1]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      # - name: Install dependencies
      #   working-directory: docker/backend
      #   run: go mod tidy

      - name: Run Go tests
        working-directory: docker/backend
        run: |
          go mod init github.com/mcbtaguiad/istio-demo/backend
          go mod tidy
          go test ./... -v

      - name: Run govulncheck
        working-directory: docker/backend
        run: |
          go mod tidy
          go mod download
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...


  # --- Python Tests ---
  monitor-test:
    needs: checkout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.8]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install flask pytest pylint black flake8 isort pytest-cov pip-audit

      - name: Run pytest
        working-directory: docker/monitor
        run: pytest . --cov=./

      - name: Lint with pylint
        working-directory: docker/monitor
        run: pylint app.py

      - name: Format check with black
        working-directory: docker/monitor
        run: black --check app.py

      - name: Import check with isort
        working-directory: docker/monitor
        run: isort --check-only app.py

      - name: Scan Python dependencies with pip-audit
        working-directory: docker/monitor
        run: pip-audit -r requirements.txt --strict

  # --- React Tests ---
  frontend-test:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: docker/frontend/package-lock.json

      - name: Install dependencies
        working-directory: docker/frontend
        run: npm ci

      - name: Run React tests
        working-directory: docker/frontend
        run: npm run test -- --coverage

      - name: Scan Node dependencies with npm audit
        working-directory: docker/frontend
        run: npm audit --audit-level=high

  # --- Docker Build & Push ---
  build:
    needs: [backend-test, monitor-test, frontend-test] # wait for all tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [frontend, backend, monitor]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set service-specific variables
        run: |
          case "${{ matrix.service }}" in
            frontend)
              echo "IMAGE_NAME=frontend" >> $GITHUB_ENV
              echo "CONTEXT=./docker/frontend" >> $GITHUB_ENV
              echo "PORT=8080" >> $GITHUB_ENV
              ;;
            backend)
              echo "IMAGE_NAME=backend" >> $GITHUB_ENV
              echo "CONTEXT=./docker/backend" >> $GITHUB_ENV
              echo "PORT=3000" >> $GITHUB_ENV
              ;;
            monitor)
              echo "IMAGE_NAME=monitor" >> $GITHUB_ENV
              echo "CONTEXT=./docker/monitor" >> $GITHUB_ENV
              echo "PORT=8000" >> $GITHUB_ENV
              ;;
          esac

      - name: Determine image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          labels: |
            org.opencontainers.image.created=${{ github.run_started_at }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=istio-demo
            org.opencontainers.image.version=${{ env.IMAGE_TAG }}
          build-args: |
            ENVIRONMENT=${{ github.ref_name == 'main' && 'prod' || 'dev' }}


  vulnerability-scan:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, monitor]
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: image
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/${{ matrix.service }}:${{ github.ref_name }}
          exit-code: '1'
          severity: HIGH,CRITICAL
          format: table
